### ISSUE TITLE
censor.net

### ISSUE THREAD

**Issue by dportvine** [ukrainianfilters/lists#10]
**Describe the bug**
Zmctrack ads

**To Reproduce**
1. Go to `https://censor.net/ua/news/3503438/rezultaty_roboty_ppo_nad_sumschynoyu`

**Expected behavior**
Ads are blocked

**Screenshots**

<details>
<summary>Screen</summary>

![2024-08-07_102559](https://github.com/user-attachments/assets/2f2c098b-b0a8-4bd1-b553-a3d3d2c98875)
</details>

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Google Chrome]
 - Version [127.0.6533.100]
 - uBO 1.59.0

**Smartphone (please complete the following information):**

**Additional context**
Add support for Chrome-based browsers.
Sites whit Zmctrack ads:

```adblock
24boxing.com.ua,avtovod.com.ua,bigmir.net,buhgalter.com.ua,buhgalter911.com,businessua.com,censor.net,dengi.ua,ditey.com,epravda.com.ua,f1analytic.com,facenews.ua,factor.ua,football-ukraine.com,footballgazeta.com,footballtransfer.com.ua,gazeta.ua,gorod.dp.ua,hvylya.net,i.ua,inforesist.org,isport.ua,ivona.ua,kolobok.ua,kriminal.tv,liga.net,meteo.ua,meteofor.com.ua,nnovosti.info,nv.ua,panno4ka.net,pogodaua.com,pravda.com.ua,real-vin.com,smak.ua,sportanalytic.com,stravy.net,tochka.net,tv.ua,viva.ua,vsetv.com,www.ukr.net,zdorovia.com.ua##+js(rmnt, script, "Shadow)
```

Also consider the possibility of creating reports as in EasyList. `https://github.com/easylist/easylist/issues/new`

**P.S>** Not all ad blocker users know English.

**Comment by serhiyguryev** [comment]
Дякую, що звернули нашу увагу на цю проблему. Ми пробаранили, що `script:has-text` й досі не підтримується браузерами на базі Chromium. Наразі видалення скриптів zfctrack.net / znctrack.net працює без проблем (commit 9a10283).

Щодо шаблону повідомлень про баги - зауваження цілком доречне. Спростимо й зробимо цей шаблон двомовним.

**Comment by dportvine** [comment]
Я не знаю, як це зроблено в [uBlock filters](https://github.com/uBlockOrigin/uAssets/tree/master/filters), але вони кожного разу не змiнюють дату вручну. Також, менi подобаеться пiдхiд до наповнення, кожен новий сайт в кiнцi списку, це дуже зручно. Рекомендую подумати над цим, поки пiдписка ще невелика. I на майбутнє, на далеке майбутнє, вони використовують для зменьшення навантаження, ось таке [Diff-Path](https://github.com/gorhill/uBlock/wiki/Dashboard%3A-Filter-lists#auto-update-filter-lists), https://github.com/gorhill/uBlock/commit/443c1f81e114df7e3c77fea7811b64224d57e8a8. А так iдея чудова, тiльки потрiбен фiдбек, без нього дiла не буде.

**Comment by serhiyguryev** [comment]
@dportvine Дата оновлення та версія фільтра - це більше інформативні коментарі і їх зручно використовувати, зокрема, при створенні запитів на виправлення помилок, щоб розуміти, про яку версію фільтра йде мова (до речі, я забув цей параметр додати до шаблону, зараз виправлю). 

Автоматичне оновлення задається в окремому коментарі і в нас це два дні. Власне, uBO (як і інші розширення або той же Brave) так само бере до уваги саме цей коментар, оскільки він для цього і створений:

> the [Expires directive](https://help.adblockplus.org/hc/en-us/articles/360062733293-How-to-write-filters#special-comments) if present in the filter list header

Щодо колективного наповнення списку. Наш підхід - сортувати правила в межах визначених логічних блоків. Так набагато зручніше проводити оптимізацію, виявляти можливі дублювання тощо. Коли правила для одного і того ж ресурсу хаотично розкидані у списку, багато часу витрачається на їхнє вивчення. За нашого ж підходу - всі правила перед очима, що значно спрощує подальшу з ними роботу.

Для тих, хто не хоче морочитися з сортуванням тощо є пісочниця: https://github.com/ukrainianfilters/lists#%D1%81%D0%BF%D1%96%D0%B2%D0%BF%D1%80%D0%B0%D1%86%D1%8F Такий підхід дозволяє закинути туди свої правила і після проходження тестування ми їх самі додаємо до списків у відповідні блоки із зазначенням авторства. Думаю, має сенс це все окремо написати також і у README проєкту.

**Comment by dportvine** [comment]
>Коли правила для одного і того ж ресурсу хаотично розкидані у списку, багато часу витрачається на їхнє вивчення.

Я мав на увазi [це](https://github.com/uBlockOrigin/uAssets/blob/master/filters/filters-2024.txt). Додавання не за алфавiтом, а кожен новий сайт в кiнцi, правила для одного сайту групуються, вони не розкидані у списку. Але то таке.. не проблема.

**Comment by dportvine** [comment]
`https://m.censor.net/ua/news/3530094/vorog-vdaryv-kabom-po-sumah`

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/5a86e9f9-fe95-4233-a236-2efbe5aa5ada)
![image](https://github.com/user-attachments/assets/7da548bd-595b-4939-8b59-e8b425daee57)
</details>

<details>
<summary>Details</summary>

```yaml
uBlock Origin: 1.62.1b1
Chromium: 131
filterset (summary):
 network: 144257
 cosmetic: 53261
 scriptlet: 27003
 html: 0
listset (total-discarded, last-updated):
 added:
  https://raw.githubusercontent.com/ukrainianfilters/lists/main/annoyances/annoyances.txt: 536-1, 43m
  ublock-annoyances: 5974-13, 43m
 default:
  user-filters: 1-0, never
  ublock-filters: 39792-118, 44m
  ublock-badware: 12153-6, 44m
  ublock-privacy: 1885-33, 44m
  ublock-unbreak: 2549-1, 44m
  ublock-quick-fixes: 224-0, 44m
  easylist: 79212-569, 44m
  easyprivacy: 53261-745, 44m
  urlhaus-1: 24020-0, 44m
  plowe-0: 3544-0, 44m
  UKR-0: 3132-130, 44m
filterset (user): [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 userFiltersTrusted: true
hiddenSettings:
 filterAuthorMode: true
supportStats:
 allReadyAfter: 826 ms
 maxAssetCacheWait: 226 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 6
 network:
  censor.net: 4
  cloudflareinsights.com: 1
  googletagmanager.com: 1
 extended:
  ##aside[style^="height: 150px;"][id], [data-campaign-id]
```
</details>

Також, прохання спростити це правило:

```adblock
censor.net##div.row.d-print-none:has(script[src^="//a4.censor.net/js/"])
```

Контент сайту пригає.

<details>
<summary>Gif</summary>

https://github.com/user-attachments/assets/1ed88761-311e-4a8e-b544-6f7627849801
</details>
