### ISSUE TITLE
Фільтри для Pi-Hole

### ISSUE THREAD

**Issue by Almightily** [ukrainianfilters/lists#114]
Доброго дня.

Зробіть, буль ласка, версію фільтрів для Pi-Hole. Приклади можна побачити тут: https://firebog.net/

**Comment by serhiyguryev** [comment]
Pi-Hole, наскільки мені відомо, підтримує виключно hosts-based списки блокувань у форматі ` 0.0.0.0 example.com` і це блокування на рівні доменів.

Наші ж списки блокувань створені з використанням синтаксису фільтрації розширення [uBlock Origin](https://ublockorigin.com/) (uBO), що є більш просунутим варіантом синтаксису Adblock. Якщо ПЗ (браузер, розширення) підтримує цей синтаксис, списки будуть працювати. При цьому, блокування відбувається на рівні запитів та обробки коду конкретних сторінок веб-ресурсів. Тому конвертувати ці списки у формат, який би підтримувався Pi-Hole - технічно неможливо.

Єдине виключення - [Ukrainian Security Filter (Український безпековий фільтр) ](https://github.com/braveinnovators/ukrainian-security-filter). Це пов'язано з тим, що 50% правил фільтрації створені саме у форматі domain-based (блокування на рівні доступу до домену). Тому тут і була можливість створити 4 формати списків, включно з hosts-based.
