### ISSUE TITLE
Помилкове блокування my.diia.gov.ua, web.monobank.ua розширенням uBlock Origin Lite

### ISSUE THREAD

**Issue by Mystic-Mirage** [ukrainianfilters/lists#148]
### Вкажіть веб-сайт(и), з якими у вас виникли проблеми

web.monobank.ua
my.diia.gov.ua

### Що відбувається?

uBlock Origin Lite повністю блокує доступ до цих сайтів коли увімкнений Ukrainian Filters

### Скриншот(и)

https://snipboard.io/gcECpm.jpg
https://snipboard.io/V1Ngo0.jpg

### Списки фільтрів, які ви використовуєте

**Які сторонні списки блокувань ви використовуєте?**

* OpenPhish Domain Blocklist https://github.com/stephenhawk8054/openphish-adblock
* Malicious URL Blocklist https://gitlab.com/malware-filter/urlhaus-filter

### Програмне забезпечення, що використовується

**Desktop:**

- ОС / версія: Xubuntu 24.04
- Браузер / версія: Google Chrome 131.0.6778.204
- Розширення блокування реклами / версія: uBlock Origin Lite 2024.12.23.23

**Comment by serhiyguryev** [comment]
Ми тестуємо правила у uBlock Origin і жодних проблем на згаданих вами сайтах не виникає, включно з Google Chrome.

Це правило для **diia.gov.ua**: `diia*.*/$document,domain=~gov.ua|~diiacityunited.org|~fedoriv.com|~spivdiia.com|~spivdiia.org.ua` Як бачите, тут вся зона gov.ua є у виключеннях.

Це правило для **monobank.ua**: `*monobank*.*/$document,domain=~monobank.com.ua|~monobank.ua` де офіційні сайти Монобанку (monobank.com.ua та monobank.ua) є у виключеннях.

![Untitled](https://github.com/user-attachments/assets/4233c6be-1c3c-4b8e-99bb-438a4be9d8e2)

Тож проблема саме у uBlock Origin Lite і у тому, що ця версія розширення має дуже обмежену функціональність, продиктовану архітектурою Manifest V3. Про це більш детально можна [прочитати тут](https://github.com/ukrainianfilters/lists?tab=readme-ov-file#%D1%81%D1%83%D0%BC%D1%96%D1%81%D0%BD%D1%96%D1%81%D1%82%D1%8C-%D0%B7-%D0%B1%D1%80%D0%B0%D1%83%D0%B7%D0%B5%D1%80%D0%B0%D0%BC%D0%B8-%D1%82%D0%B0-%D1%80%D0%BE%D0%B7%D1%88%D0%B8%D1%80%D0%B5%D0%BD%D0%BD%D1%8F%D0%BC%D0%B8).

У цьому випадку варто звернутися до розробників Lite-версії uBlock Origin. Або ж змінити браузер, оскільки Google Chrome вже з червня почав деактивувати розширення, що не підтримують Manifest V3.

**Comment by Mystic-Mirage** [comment]
Але тиждень-два тому усе працювало...

**Comment by Mystic-Mirage** [comment]
Але тиждень-два тому усе працювало. І як раз декілька днів тому до цих правил були внесені зміни https://github.com/ukrainianfilters/lists/commit/d37dd1376ac3c7fa8189aae1ec7406c5fadfc575

**Comment by Mystic-Mirage** [comment]
Зарепортив їм, подивимось що скажуть -- https://github.com/uBlockOrigin/uAssets/issues/26604

**Comment by serhiyguryev** [comment]
> І як раз декілька днів тому до цих правил були внесені зміни [d37dd13](https://github.com/ukrainianfilters/lists/commit/d37dd1376ac3c7fa8189aae1ec7406c5fadfc575)

Суть цих змін полягає у тому, що не будуть блокуватися URL типу `site.com/diia/page.html`. З реальних прикладів - до цих змін блокувалося посилання на статтю `itc.ua` про нову пошту, у назві якої було `nova-poshta`. Тому і потрібно відсікати такі випадки за допомогою цього фрагменту `*.*/`. Оновлені паттерни створені з використанням звичайного синтаксису, який добре розуміє повноцінна версія uBlock Origin (Manifest V2).

Тому тут точно проблема не в цих правилах, а у тому, як їх обробляє версія Lite.

**Comment by serhiyguryev** [comment]
Оскільки рішення проблеми [знайдено](https://github.com/uBlockOrigin/uAssets/issues/26604#issuecomment-2561241093), зараз оновимо правила.

**Comment by serhiyguryev** [comment]
Правила оновлені згідно отриманих рекомендацій. Сподіваюся, тепер у Lite версії все має працювати так, як треба.

**Comment by myroslavandriychuk** [comment]
> Зараз блокує лінки на банки монобанку в uBO light

Ми оновили правила згідно рекомендацій, які отримали тут: https://github.com/uBlockOrigin/uAssets/issues/26604#issuecomment-2561241093

Проблема, яка виникає у користувачів Lite версії uBlock Origin (Manifest V3), жодним чином не пов'язана з нашими правилами фільтрації, оскільки вони створені відповідно до стандартизованого синтаксису uBlock Origin і у користувачів uBlock Origin (Manifest V2) такі проблеми відсутні. Про це написали і розробники розширення - тут питання до сумісності Lite версії та Manifest V3.

Тому у вас є наступні варіанти:

1. Дочекатися оновлення Lite версії uBlock Origin; якщо оновлена версія не усуває проблему - потрібно звернутися до розробників Lite версії uBlock Origin (ми тут нічого не можемо зробити)
2. Замінити браузер на Firefox або на браузер, що заснований на Chromium і який продовжить [підтримувати Manifest V2](https://github.com/ukrainianfilters/lists?tab=readme-ov-file#%D1%81%D1%83%D0%BC%D1%96%D1%81%D0%BD%D1%96%D1%81%D1%82%D1%8C-%D0%B7-%D0%B1%D1%80%D0%B0%D1%83%D0%B7%D0%B5%D1%80%D0%B0%D0%BC%D0%B8-%D1%82%D0%B0-%D1%80%D0%BE%D0%B7%D1%88%D0%B8%D1%80%D0%B5%D0%BD%D0%BD%D1%8F%D0%BC%D0%B8)

**Comment by serhiyguryev** [comment]
@bak1an останньою версією uBlock Origin Lite є [2024.12.23.23](https://chromewebstore.google.com/detail/ublock-origin-lite/ddkjiahejlhfcafbddmgiahcphecmpfh) від 23.12.2024.

Про згадану вами проблему було повідомлено 24.12.2024 тут: https://github.com/uBlockOrigin/uAssets/issues/26604

Тому слід дочекатися оновленої версії розширення, оскільки правила під Manifest V3 розробники uBO Lite прописують вручну.

**Comment by Mystic-Mirage** [comment]
@bak1an Workaround наразі це виключити Ukrainian Filters та дочекатися оновлення uBOL

**Comment by myroslavandriychuk** [comment]
Сьогодні з'явилася версія uBO Lite 2024.12.30.1320. В мене проблем з відкриттям `web.monobank.ua` та 
`my.diia.gov.ua` немає.

**Comment by Mystic-Mirage** [comment]
Підтверджую. Після оновлення проблема більше не спостерігається

Закриваю

**Comment by mourner** [comment]
На останній версії (2024.12.30) дійсно пофіксили Монобанк і Дію, але деякі вебсайти все ще блокує — наприклад, raiffeisen.ua.

**Comment by serhiyguryev** [comment]
> Питаю про це, тому що були змінені посилання на точки авторизації і нам довелося оновити правила, щоб вони коректно відпрацьовували по декільком банкам, включно з Райффайзен (ці правила відсутні у поточній версії uBOL). Але це стосується виключно BankID

У версії 2025.1.7.268 від 08 січня це оновлення вже є і переадресації BankID відбуваються без блокувань

**Comment by mourner** [comment]
@serhiyguryev перевірив — на цій останній версії досі блокується бізнес-клієнт-банк на rbo.raiffeisen.ua:

<img width="979" alt="image" src="https://github.com/user-attachments/assets/e2955f16-a8ad-48ca-ba4c-76730a418485" />

**Comment by myroslavandriychuk** [comment]
> на цій останній версії досі блокується бізнес-клієнт-банк на rbo.raiffeisen.ua:

Причиною цьому є ця чудова URL-адреса: `https://rbo.raiffeisen.ua/auth/realms/raif-external/protocol/openid-connect/auth?response_type=code&client_id=rbo&scope=openid&state=VfgYpLrrX91CA1tcYDi92H_r1i7ZsvDLOfzgWWBkjX4%3D&redirect_uri=https://rbo.raiffeisen.ua/ibank/login/oauth2/code/keycloak&nonce=4u1qVN8dKHp-iR9z9_aDWJC9273_CxZYV7GCa5rHS6E&code_challenge=gow4FIM8G5GTbB-jSEL8V00O5oPDRKqF7iEcUFv1ps4&code_challenge_method=S256` через яку спрацьовує одне з правил фільтрації, а саме: `raif-*.*.$document`

@serhiyguryev я зараз зроблю оновлення і для Райффайзен, і, превентивно, для інших банків по другорядним правилам фільтрації.

**Comment by serhiyguryev** [comment]
> Причиною цьому є ця чудова URL-адреса

Це капець, яка краса

**Comment by myroslavandriychuk** [comment]
Проблема з `rbo.raiffeisen.ua` виправлена, очікуємо нову версію uBOL

**Comment by mourner** [comment]
Дуже дякую за оперативний фікс!

**Comment by serhiyguryev** [comment]
@mourner версія 2025.1.14.952 uBlock Origin Lite вже "підтягнула" оновлену версію наших фільтрів, тож `rbo.raiffeisen.ua` відкривається без проблем
