### ISSUE TITLE
drovae.gov.ua

### ISSUE THREAD

**Issue by Skrriply** [ukrainianfilters/lists#27]
#### Вкажіть веб-сайт(и), з якими у вас виникли проблеми
```
https://drovae.gov.ua/
```

#### Що відбувається?
Банер про файли cookie

#### Скриншот(и)
![cookies](https://github.com/user-attachments/assets/afa99b0d-9768-4f6e-a98f-2c41bb5b3056)

#### Списки фільтрів, які ви використовуєте
Ukrainian Annoyance Filter (24.08.19)

**Які сторонні списки блокувань ви використовуєте?**
Немає

**Які саме Ukrainian Filters (Українські фільтри) ви використовуєте?**
Ukrainian Annoyance Filter (24.08.19)

#### Програмне забезпечення, що використовується

**Smartphone:**

- Пристрій: Realme 6
- ОС / версія: Android 11
- Браузер / версія: FireFox 128.0.3
- Розширення блокування реклами / версія: uBlock Origin 1.59.0

#### Додаткова інформація
Немає

**Comment by yarynanowak** [comment]
Виправлено pull request #30
