### ISSUE TITLE
results.medis.com.ua

### ISSUE THREAD

**Issue by Skrriply** [ukrainianfilters/lists#28]
#### Вкажіть веб-сайт(и), з якими у вас виникли проблеми
```
https://results.medis.com.ua/login/index.php
```

#### Що відбувається?
Банер про файли cookie

#### Скриншот(и)
![cook1es](https://github.com/user-attachments/assets/3392a0e1-e6db-42bc-b3b6-913adfddfbb2)

#### Списки фільтрів, які ви використовуєте
Ukrainian Annoyance Filter (24.08.19)

**Які сторонні списки блокувань ви використовуєте?**
Немає

**Які саме Ukrainian Filters (Українські фільтри) ви використовуєте?**
Ukrainian Annoyance Filter (24.08.19)

#### Програмне забезпечення, що використовується
**Smartphone:**

- Пристрій: Realme 6
- ОС / версія: Android 11
- Браузер / версія: FireFox 128.0.3
- Розширення блокування реклами / версія: uBlock Origin 1.59.0

#### Додаткова інформація
Немає

**Comment by yarynanowak** [comment]
Виправлено pull request #30
