### ISSUE TITLE
foundation.ua

### ISSUE THREAD

**Issue by Skrriply** [ukrainianfilters/lists#29]
#### Вкажіть веб-сайт(и), з якими у вас виникли проблеми
```
https://foundation.ua/
```

#### Що відбувається?
Банер про файли cookie

#### Скриншот(и)
![cookie](https://github.com/user-attachments/assets/46cdc7d2-60f1-4329-8c05-8d72c2972b73)

#### Списки фільтрів, які ви використовуєте
Ukrainian Annoyance Filter (24.08.19)

**Які сторонні списки блокувань ви використовуєте?**
Немає

**Які саме Ukrainian Filters (Українські фільтри) ви використовуєте?**
Ukrainian Annoyance Filter (24.08.19)

#### Програмне забезпечення, що використовується
**Smartphone:**

- Пристрій: Realme 6
- ОС / версія: Android 11
- Браузер / версія: FireFox 128.0.3
- Розширення блокування реклами / версія: uBlock Origin 1.59.0

#### Додаткова інформація
Немає

**Comment by yarynanowak** [comment]
У версії фільтра 24.08.20 правило ##.cookie винесено у секцію загальних правил (ці правила не прив'язані до конкретних доменів), тож на цьому сайті це повідомлення вже блокується (потрібно оновити фільтр).
