### ISSUE TITLE
my.ua

### ISSUE THREAD

**Issue by Skrriply** [ukrainianfilters/lists#34]
### Вкажіть веб-сайт(и), з якими у вас виникли проблеми
```
https://my.ua/
```

### Що відбувається?
Банер про файли cookie

### Скриншот(и)
![bnr](https://github.com/user-attachments/assets/87bc8e18-d050-42ca-9f7e-8785ca075ef4)

### Списки фільтрів, які ви використовуєте
**Які саме Ukrainian Filters (Українські фільтри) ви використовуєте?**
Ukrainian Annoyance Filter (24.08.28)

**Які сторонні списки блокувань ви використовуєте?**
Немає

### Програмне забезпечення, що використовується
**Smartphone:**

- Пристрій: Realme 6
- ОС / версія: Android 11
- Браузер / версія: FireFox 128.0.3
- Розширення блокування реклами / версія: uBlock Origin 1.59.0

### Додаткова інформація
Немає

**Comment by yarynanowak** [comment]
Виправлено: pull request #36
