### ISSUE TITLE
Сайти громад

### ISSUE THREAD

**Issue by Skrriply** [ukrainianfilters/lists#35]
### Вкажіть веб-сайт(и), з якими у вас виникли проблеми
```
Сайтів існує багато, ось декілька з них:
https://sofotg.gov.ua/
https://dnrada.gov.ua/
https://sosnitsa-rada.gov.ua/
https://tupychiv-rada.gov.ua/
https://khotyn.dosvit.org.ua/
```

### Що відбувається?
Банер про файли cookie

### Скриншот(и)
![gromada](https://github.com/user-attachments/assets/637c35b2-daf3-4385-958e-ba94de875f8d)

### Списки фільтрів, які ви використовуєте

**Які саме Ukrainian Filters (Українські фільтри) ви використовуєте?**
Ukrainian Annoyance Filter (24.08.28)

**Які сторонні списки блокувань ви використовуєте?**
Немає

### Програмне забезпечення, що використовується
**Smartphone:**

- Пристрій: Realme 6
- ОС / версія: Android 11
- Браузер / версія: Firefox 128.0.3
- Розширення блокування реклами / версія: uBlock Origin 1.59.0

### Додаткова інформація
Цей фільтр вирішує проблему.
Можливо це допоможе)
```
gov.ua,dosvit.org.ua##+js(set-cookie, gdprClosed, false)
```

**Comment by yarynanowak** [comment]
Виправлено: pull request #36
