### ISSUE TITLE
internetua.com

### ISSUE THREAD

**Issue by Skrriply** [ukrainianfilters/lists#47]
### Вкажіть веб-сайт(и), з якими у вас виникли проблеми
```
https://internetua.com/reportera-z-vaiomingu-spiimali-na-vikoristanni-shi-dlya-stvorennya-falshivih-citat-ta-istorii
```

### Що відбувається?
Реклама

### Скриншот(и)
![зображення](https://github.com/user-attachments/assets/0485f99a-a7b0-401f-8944-5f29da496d32)

### Списки фільтрів, які ви використовуєте

**Які саме Ukrainian Filters (Українські фільтри) ви використовуєте?**
Ukrainian Security Filter (24.08.3)
Ukrainian Ad Filter (24.08.47)
Ukrainian Annoyance Filter (24.08.41)
Ukrainian Privacy Filter (24.08.40)

**Які сторонні списки блокувань ви використовуєте?**
uBlock Filters
EasyList (Thu, 15 Aug 2024 07:24:44 +0000)
EasyPrivacy (Thu, 15 Aug 2024 02:24:33 +0000)
Actually Legitimate URL Shortener Tool (12August2024v1)
Block Outsider Intrusion into LAN (Sun, 11 Aug 2024 00:57:20 +0000)
Block third party fonts (12 August 2024)
HaGeZi's Pro mini DNS/Browser Blocklist (2024.0814.0136.38)

### Програмне забезпечення, що використовується

**Desktop:**

- ОС / версія: Linux
- Браузер / версія: LibreWolf 129.0.1-1
- Розширення блокування реклами / версія: uBlock Origin 1.59.0

### Додаткова інформація
Немає

**Comment by serhiyguryev** [comment]
Тепер реклама блокується: https://github.com/ukrainianfilters/lists/commit/914bbe74732363c421369f027425444c831316c5
