### ISSUE TITLE
real-vin.com

### ISSUE THREAD

**Issue by Skrriply** [ukrainianfilters/lists#49]
### Вкажіть веб-сайт(и), з якими у вас виникли проблеми
```
https://real-vin.com/
```

### Що відбувається?
Реклама та погодний віджет

### Скриншот(и)
![зображення](https://github.com/user-attachments/assets/18a3d5ce-8ace-41a9-847f-0bad6aabdc45)
![зображення](https://github.com/user-attachments/assets/017410a7-3a1b-455e-9c6f-a0524c4fadce)

### Списки фільтрів, які ви використовуєте

**Які саме Ukrainian Filters (Українські фільтри) ви використовуєте?**
Ukrainian Ad Filter (24.08.52)
Ukrainian Annoyance Filter (24.08.52)
Ukrainian Privacy Filter (24.08.52)
Ukrainian Security Filter (24.08.3)

**Які сторонні списки блокувань ви використовуєте?**
uBlock Filters
EasyList (Sun, 18 Aug 2024 13:11:58 +0000)
EasyPrivacy (Sun, 18 Aug 2024 10:24:01 +0000)
Actually Legitimate URL Shortener Tool (12August2024v1)
Block Outsider Intrusion into LAN (Sun, 11 Aug 2024 00:57:20 +0000)
Block third party fonts (14 August 2024)
HaGeZi's Pro mini DNS/Browser Blocklist (2024.0818.0146.40)

### Програмне забезпечення, що використовується

**Desktop:**

- ОС / версія: Linux
- Браузер / версія: LibreWolf 129.0.1-1
- Розширення блокування реклами / версія: uBlock Origin 1.59.0

### Додаткова інформація
Немає

**Comment by serhiyguryev** [comment]
Виправлено: https://github.com/ukrainianfilters/lists/commit/af592f3b8b9cb65f8a957dd469d800f8e13b6ac0

**Comment by dportvine** [comment]
Реклама

`https://real-vin.com/okupanti-zahopili-novi-teritorii-na-donechchini-10`

<details>
<summary>Скриншот(и)</summary>

![Image](https://github.com/user-attachments/assets/6f4963e3-94a5-44e7-9c18-66e8297ec648)
</details>
