### ISSUE TITLE
Правила domains

### ISSUE THREAD

**Issue by pomazanbohdan** [ukrainianfilters/lists#7]
Чи є таке що можна блокувати правилами блокування доменів?

1. Використовувати на локальных dns серверах (pi-hole/)
2. На мобільному через додаток AdAway

**Comment by pomazanbohdan** [comment]
![Screenshot_2024-08-04-11-21-25-947_org adaway](https://github.com/user-attachments/assets/67c081a6-6838-4f8c-a802-1530d7fcaf21)
Чого питаю бо жоден зі списків не опрацьовується

**Comment by serhiyguryev** [comment]
Hosts-based версію має лише Український безпековий фільтр: [https://github.com/braveinnovators/ukrainian-security-filter](https://github.com/braveinnovators/ukrainian-security-filter)

Щодо інших фільтрів. Фільтри Ad, Annoyance та Privacy технічно неможливо реалізувати у такому форматі, оскільки всі операції (видалення, зміна або приховування елементів, стилів, скриптів) відбуваються на рівні конкретних веб-сторінок, а не доменів. Так, є певні правила фільтрації щодо доменів, але це блокування на специфічному рівні: third-party, xmlhttprequest, script. Це не блокування домену у цілому (таких правил, якщо не помиляюся, лише два і лише у Ukrainian Ad Filter).

**Comment by yarynanowak** [comment]
@pomazanbohdan Android-версія Firefox надає можливість встановлювати розширення, тому ви можете без проблем встановити [uBlock Origin](https://ublockorigin.com/) та імпортувати всі 4 фільтри. Якщо вас не влаштовує Firefox або у вас iOS (під якою Firefox не підтримує розширення), раджу розглянути можливість встановлення браузера [Brave](https://brave.com/).

**Comment by serhiyguryev** [comment]
Цей запит закривається, оскільки виконати його технічно неможливо: https://github.com/ukrainianfilters/lists/issues/7#issuecomment-2267530642
